# Generated by Django 4.2.11 on 2024-03-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Categoty", new_name="Category",),
    ]
